### ISSUE TITLE
Merge conflict issues with README

### ISSUE THREAD

**Issue by mhart** [ql-io/cluster2#1]
Not sure what's gone on, but it looks like there's been a merge conflict in README that hasn't been cleaned up.

I'm not familiar enough with the project to know what to keep and what not to so I haven't made a pull request.

```
<<<<<<< HEAD Completion of `shutdown()` does not necessarily mean that all worker processes...
```

etc...

**Comment by s3u** [comment]
Thanks for noticing. Fixed.
