### ISSUE TITLE
Dependency with express 2.5.9 break installation

### ISSUE THREAD

**Issue by xbeaudouin** [ql-io/cluster2#11]
Hi !

I would like to install that to my node 0.8.3 on freebsd, but the dependecy with express 2.5.9 is a pain because it cannot be install with node > 0.8.3

This is pain because cluster2 thus is not able to work on node > 0.7.0 -> bad

How I can solve that ?

Xavier

npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: express@2.5.9
npm ERR! Required: {"node":">= 0.4.1 < 0.7.0"}
npm ERR! Actual:   {"npm":"1.1.21","node":"0.8.3"}
npm ERR! 
npm ERR! System FreeBSD 9.0-RELEASE-p3
npm ERR! command "node" "/usr/local/bin/npm" "install" "cluster2"
npm ERR! cwd /home/kiwi/git/DNSwitness/DNSmezzo/reports
npm ERR! node -v v0.8.3
npm ERR! npm -v 1.1.21
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kiwi/git/DNSwitness/DNSmezzo/reports/npm-debug.log
npm not ok

**Comment by shimonchayim** [comment]
Builds issues seem to be resolved now.
