### ISSUE TITLE
Why the server requirement?

### ISSUE THREAD

**Issue by cmawhorter** [ql-io/cluster2#2]
I just started looking at cluster2 so I may be missing something, but it seems like for cli, it would be nice if we could do something like:

var c = new Cluster;

c.worker(function(pid) {
   zmq_sock.on('message', function(msg) {
       console.log(pid + ' ' + msg.toString());
   });
});

... or even pass in a js file ...

c.worker('./worker.js');

The web/tcp servers could then run on top of this type of setup.

**Comment by shimonchayim** [comment]
Please feel free to send a pull request. We can review and merge it.
